"""add names in cart table

Revision ID: 2f7f79feca6d
Revises: b3db5fdea704
Create Date: 2025-09-22 20:13:59.742934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7f79feca6d'
down_revision: Union[str, Sequence[str], None] = 'b3db5fdea704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'name')
    # ### end Alembic commands ###
